---
title: "final_data"
author: "David"
date: "2024-05-04"
output: 
  html_document:
    css: styles.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(readxl)
library(dplyr)
library(ggplot2)
library(caret)
library(pROC)
library(gbm)
library(randomForest)
library(MASS)
library(stringr)
```

```{r, color_definitions}

primary_color = "#CC0000"
secondary_color = "black"

```

```{r}
# Load the data
final_data <- read_excel("e_data.xlsx")
```

```{r}
final_data
```

```{r}
#check missing values
sum(is.na(final_data))
```

```{r}
#filter out Ethnicity and keep only Hispanic/Latino and E_cigarette_ever to yes and drop these two columns
final_data <- final_data %>% filter(Ethnicity == "Hispanic/Latino")
final_data <- final_data %>% filter(E_cigarette_ever == "Yes")
final_data <- final_data %>% dplyr::select(-Ethnicity, -E_cigarette_ever)
#change the smoking_habbit to smoking_habit
final_data <- final_data %>% rename(smoking_habit = smoking_habbit)
final_data
```

```{r}
#filter out Reason_feel_relaxed from never tried
final_data <- final_data %>% filter(Reason_feel_relaxed != "never tried")
final_data
```

```{r}
#smoking_habit
final_data$smoking_habit <- as.factor(final_data$smoking_habit)
#ratio
count_by_smoking_habit <- final_data %>%
  group_by(smoking_habit) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))
count_by_smoking_habit

#plotting
ggplot(final_data, aes(x = smoking_habit)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "smoking_habit",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

```


```{r, Year}
final_data$Year <- as.factor(final_data$Year)
#ratio
count_by_year <- final_data %>%
  group_by(Year) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))
count_by_year
#arrange Year by freshmen, sophomore, junior, senior, graduate
final_data$Year <- factor(final_data$Year, levels = c("Freshman", "Sophomore", "Junior", "Senior", "Graduate"))


#plotting from freshman to graduate
ggplot(final_data, aes(x = Year)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution of Year",
       x = "Year",
       y = "Count") + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()

#plot the distribution of the variable by smoking_habit
ggplot(
  final_data, 
  aes(
    x = Year, # Change this to variable name
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Year",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Gender
final_data$Gender <- as.factor(final_data$Gender)
#ratio
count_by_Gender <- final_data %>%
  group_by(Gender) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))
count_by_Gender

#plotting
ggplot(final_data, aes(x = Gender)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Gender",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()
  
#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Gender, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Gender",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)
  ) + 
  theme_bw()
       

```

```{r}
#Relationship
final_data$Relationship <- as.factor(final_data$Relationship)
#ratio
count_by_Relationship <- final_data %>%
  group_by(Relationship) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))
count_by_Relationship

#plotting
ggplot(final_data, aes(x = Relationship)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Relationship",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habit
ggplot(
  final_data, 
  aes(
    x = Relationship, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Relationship",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#ever_smoked_100_cig
final_data$ever_smoked_100_cig <- as.factor(final_data$ever_smoked_100_cig)
#ratio
count_by_ever_smoked_100_cig <- final_data %>%
  group_by(ever_smoked_100_cig) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_ever_smoked_100_cig

#plotting
ggplot(final_data, aes(x = ever_smoked_100_cig)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "ever_smoked_100_cig",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habit
ggplot(
  final_data, 
  aes(
    x = ever_smoked_100_cig, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "ever_smoked_100_cig",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#smoke_cigarettes_now
final_data$smoke_cigarettes_now <- as.factor(final_data$smoke_cigarettes_now)
#ratio
count_by_smoke_cigarettes_now <- final_data %>%
  group_by(smoke_cigarettes_now) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_smoke_cigarettes_now

#plotting
ggplot(final_data, aes(x = smoke_cigarettes_now)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "smoke_cigarettes_now",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habit
ggplot(
  final_data, 
  aes(
    x = smoke_cigarettes_now, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "smoke_cigarettes_now",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Smoking_Plan
final_data$Smoking_Plan <- as.factor(final_data$Smoking_Plan)
#ratio
count_by_Smoking_Plan <- final_data %>%
  group_by(Smoking_Plan) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Smoking_Plan

#plotting
ggplot(final_data, aes(x = Smoking_Plan)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Smoking_Plan",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habit
ggplot(
  final_data, 
  aes(
    x = Smoking_Plan, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Smoking_Plan",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#SocialMedia
final_data$SocialMedia <- as.factor(final_data$SocialMedia)
#ratio
count_by_SocialMedia <- final_data %>%
  group_by(SocialMedia) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_SocialMedia

#plotting
ggplot(final_data, aes(x = SocialMedia)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "SocialMedia",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = SocialMedia, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "SocialMedia",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Marijuana
final_data$Marijuana <- as.factor(final_data$Marijuana)
#ratio
count_by_Marijuana <- final_data %>%
  group_by(Marijuana) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Marijuana

#plotting
ggplot(final_data, aes(x = Marijuana)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Marijuana",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Marijuana, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Marijuana",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Total_Days_marijuana
final_data$Total_Days_marijuana <- as.factor(final_data$Total_Days_marijuana)
#ratio
count_by_Total_Days_marijuana <- final_data %>%
  group_by(Total_Days_marijuana) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Total_Days_marijuana

#plotting
ggplot(final_data, aes(x = Total_Days_marijuana)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Total_Days_marijuana",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Total_Days_marijuana, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Total_Days_marijuana",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Alcohol
final_data$Alcohol <- as.factor(final_data$Alcohol)
#ratio
count_by_Alcohol <- final_data %>%
  group_by(Alcohol) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Alcohol

#plotting
ggplot(final_data, aes(x = Alcohol)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Alcohol",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Alcohol, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Alcohol",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Alcohol_habbit
final_data$Alcohol_habbit <- as.factor(final_data$Alcohol_habbit)
#ratio
count_by_Alcohol_habbit <- final_data %>%
  group_by(Alcohol_habbit) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Alcohol_habbit

#plotting
ggplot(final_data, aes(x = Alcohol_habbit)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Alcohol_habbit",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Alcohol_habbit, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Alcohol_habbit",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Injurious (Nicotine e-cigarette or electronic vaping product are less harmful than tobacco cigarettes)
final_data$Injurious <- as.factor(final_data$Injurious)
#ratio
count_by_Injurious <- final_data %>%
  group_by(Injurious) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Injurious

#plotting
ggplot(final_data, aes(x = Injurious)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Injurious",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Injurious, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Injurious",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_enjoyed_it
unique(final_data$Reason_enjoyed_it)
final_data$Reason_enjoyed_it <- as.factor(final_data$Reason_enjoyed_it)
#ratio
count_by_Reason_enjoyed_it <- final_data %>%
  group_by(Reason_enjoyed_it) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_enjoyed_it

#plotting
ggplot(final_data, aes(x = Reason_enjoyed_it)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_enjoyed_it",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_enjoyed_it, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_enjoyed_it",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_feel_relaxed
unique(final_data$Reason_feel_relaxed)
final_data$Reason_feel_relaxed <- as.factor(final_data$Reason_feel_relaxed)
#ratio
count_by_Reason_feel_relaxed <- final_data %>%
  group_by(Reason_feel_relaxed) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_feel_relaxed

#plotting
ggplot(final_data, aes(x = Reason_feel_relaxed)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_feel_relaxed",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_feel_relaxed, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_feel_relaxed",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_feel_good
unique(final_data$Reason_feel_good)
final_data$Reason_feel_good <- as.factor(final_data$Reason_feel_good)
#ratio
count_by_Reason_feel_good <- final_data %>%
  group_by(Reason_feel_good) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_feel_good

#plotting
ggplot(final_data, aes(x = Reason_feel_good)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_feel_good",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_feel_good, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_feel_good",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_feel_less_stressed
unique(final_data$Reason_feel_less_stressed)
final_data$Reason_feel_less_stressed <- as.factor(final_data$Reason_feel_less_stressed)
#ratio
count_by_Reason_feel_less_stressed <- final_data %>%
  group_by(Reason_feel_less_stressed) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_feel_less_stressed

#plotting
ggplot(final_data, aes(x = Reason_feel_less_stressed)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_feel_less_stressed",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_feel_less_stressed, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_feel_less_stressed",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_socially_acceptable
unique(final_data$Reason_socially_acceptable)
final_data$Reason_socially_acceptable <- as.factor(final_data$Reason_socially_acceptable)
#ratio
count_by_Reason_socially_acceptable <- final_data %>%
  group_by(Reason_socially_acceptable) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_socially_acceptable

#plotting
ggplot(final_data, aes(x = Reason_socially_acceptable)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_socially_acceptable",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_socially_acceptable, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_socially_acceptable",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_cool_trandy
unique(final_data$Reason_cool_trandy)
final_data$Reason_cool_trandy <- as.factor(final_data$Reason_cool_trandy)
#ratio
count_by_Reason_cool_trandy <- final_data %>%
  group_by(Reason_cool_trandy) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_cool_trandy

#plotting
ggplot(final_data, aes(x = Reason_cool_trandy)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_cool_trandy",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_cool_trandy, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_cool_trandy",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_gain_respect
unique(final_data$Reason_gain_respect)
final_data$Reason_gain_respect <- as.factor(final_data$Reason_gain_respect)
#ratio
count_by_Reason_gain_respect <- final_data %>%
  group_by(Reason_gain_respect) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_gain_respect

#plotting
ggplot(final_data, aes(x = Reason_gain_respect)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_gain_respect",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_gain_respect, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_gain_respect",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_become_popular
unique(final_data$Reason_become_popular)
final_data$Reason_become_popular <- as.factor(final_data$Reason_become_popular)
#ratio
count_by_Reason_become_popular <- final_data %>%
  group_by(Reason_become_popular) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_become_popular

#plotting
ggplot(final_data, aes(x = Reason_become_popular)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_become_popular",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_become_popular, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_become_popular",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_avoid_bothering
unique(final_data$Reason_avoid_bothering)
final_data$Reason_avoid_bothering <- as.factor(final_data$Reason_avoid_bothering)
#ratio
count_by_Reason_avoid_bothering <- final_data %>%
  group_by(Reason_avoid_bothering) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_avoid_bothering

#plotting
ggplot(final_data, aes(x = Reason_avoid_bothering)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_avoid_bothering",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_avoid_bothering, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_avoid_bothering",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_reduce_tobacco
unique(final_data$Reason_reduce_tobacco)
final_data$Reason_reduce_tobacco <- as.factor(final_data$Reason_reduce_tobacco)
#ratio
count_by_Reason_reduce_tobacco <- final_data %>%
  group_by(Reason_reduce_tobacco) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_reduce_tobacco

#plotting
ggplot(final_data, aes(x = Reason_reduce_tobacco)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_reduce_tobacco",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_reduce_tobacco, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_reduce_tobacco",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_quit_smoking
unique(final_data$Reason_quit_smoking)
final_data$Reason_quit_smoking <- as.factor(final_data$Reason_quit_smoking)
#ratio
count_by_Reason_quit_smoking <- final_data %>%
  group_by(Reason_quit_smoking) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_quit_smoking

#plotting
ggplot(final_data, aes(x = Reason_quit_smoking)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_quit_smoking",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_quit_smoking, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_quit_smoking",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_craving_tobacco
unique(final_data$Reason_craving_tobacco)
final_data$Reason_craving_tobacco <- as.factor(final_data$Reason_craving_tobacco)
#ratio
count_by_Reason_craving_tobacco <- final_data %>%
  group_by(Reason_craving_tobacco) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_craving_tobacco

#plotting
ggplot(final_data, aes(x = Reason_craving_tobacco)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_craving_tobacco",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_craving_tobacco, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_craving_tobacco",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_less_toxic
unique(final_data$Reason_less_toxic)
final_data$Reason_less_toxic <- as.factor(final_data$Reason_less_toxic)
#ratio
count_by_Reason_less_toxic <- final_data %>%
  group_by(Reason_less_toxic) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_less_toxic

#plotting
ggplot(final_data, aes(x = Reason_less_toxic)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_less_toxic",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_less_toxic, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_less_toxic",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_smell_like_smoke
unique(final_data$Reason_smell_like_smoke)
final_data$Reason_smell_like_smoke <- as.factor(final_data$Reason_smell_like_smoke)
#ratio
count_by_Reason_smell_like_smoke <- final_data %>%
  group_by(Reason_smell_like_smoke) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_smell_like_smoke

#plotting
ggplot(final_data, aes(x = Reason_smell_like_smoke)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_smell_like_smoke",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_smell_like_smoke, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_smell_like_smoke",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_cheaper_than_tobacco
unique(final_data$Reason_cheaper_than_tobacco)
final_data$Reason_cheaper_than_tobacco <- as.factor(final_data$Reason_cheaper_than_tobacco)
#ratio
count_by_Reason_cheaper_than_tobacco <- final_data %>%
  group_by(Reason_cheaper_than_tobacco) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_cheaper_than_tobacco

#plotting
ggplot(final_data, aes(x = Reason_cheaper_than_tobacco)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_cheaper_than_tobacco",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_cheaper_than_tobacco, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_cheaper_than_tobacco",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#Reason_flavors
unique(final_data$Reason_flavors)
final_data$Reason_flavors <- as.factor(final_data$Reason_flavors)
#ratio
count_by_Reason_flavors <- final_data %>%
  group_by(Reason_flavors) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_Reason_flavors

#plotting
ggplot(final_data, aes(x = Reason_flavors)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "Reason_flavors",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = Reason_flavors, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "Reason_flavors",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#e_HeartAttack_stroke_coronary
unique(final_data$e_HeartAttack_stroke_coronary)
final_data$e_HeartAttack_stroke_coronary <- as.factor(final_data$e_HeartAttack_stroke_coronary)
#ratio
count_by_e_HeartAttack_stroke_coronary <- final_data %>%
  group_by(e_HeartAttack_stroke_coronary) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_e_HeartAttack_stroke_coronary

#plotting
ggplot(final_data, aes(x = e_HeartAttack_stroke_coronary)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "e_HeartAttack_stroke_coronary",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = e_HeartAttack_stroke_coronary, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "e_HeartAttack_stroke_coronary",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#e_Seizures
unique(final_data$e_Seizures)
final_data$e_Seizures <- as.factor(final_data$e_Seizures)
#ratio
count_by_e_Seizures <- final_data %>%
  group_by(e_Seizures) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_e_Seizures

#plotting
ggplot(final_data, aes(x = e_Seizures)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "e_Seizures",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = e_Seizures, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "e_Seizures",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#e_Depression
unique(final_data$e_Depression)
final_data$e_Depression <- as.factor(final_data$e_Depression)
#ratio
count_by_e_Depression <- final_data %>%
  group_by(e_Depression) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_e_Depression

#plotting
ggplot(final_data, aes(x = e_Depression)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "e_Depression",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = e_Depression, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "e_Depression",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#e_lung_disease
unique(final_data$e_lung_disease)
final_data$e_lung_disease <- as.factor(final_data$e_lung_disease)
#ratio
count_by_e_lung_disease <- final_data %>%
  group_by(e_lung_disease) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_e_lung_disease

#plotting
ggplot(final_data, aes(x = e_lung_disease)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "e_lung_disease",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = e_lung_disease, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "e_lung_disease",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#e_no_risk
unique(final_data$e_no_risk)
final_data$e_no_risk <- as.factor(final_data$e_no_risk)
#ratio
count_by_e_no_risk <- final_data %>%
  group_by(e_no_risk) %>%
  summarise(Count = n()) %>%
  mutate(Ratio = paste0(round(100 * Count / sum(Count), 1), "%"))

count_by_e_no_risk

#plotting
ggplot(final_data, aes(x = e_no_risk)) +
  geom_bar(fill = primary_color, color = "black") +
  labs(title = "Distribution",
       x = "e_no_risk",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) +
  theme_bw()

#plot the distribution of the variable by smoking_habbit
ggplot(
  final_data, 
  aes(
    x = e_no_risk, 
    fill = smoking_habit
  )
) +
  geom_bar(
    position = "fill"
  ) +
  labs(
       x = "e_no_risk",
       y = "Proportion"
  ) +
  scale_fill_manual(
    values = c(
      secondary_color, # Defined colors
      primary_color
    )
  ) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5)) + 
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) + 
  theme_bw()
```

```{r}
#drop the columns and save the data
final_data <- final_data %>%
  dplyr::select(-c(Year, Relationship, smoke_cigarettes_now, Total_Days_marijuana, Reason_become_popular, Reason_gain_respect, Reason_avoid_bothering, Reason_reduce_tobacco, Reason_quit_smoking, Reason_craving_tobacco, Reason_less_toxic, Reason_cheaper_than_tobacco, e_no_risk))

final_data


```

```{r}
#save the data in excel
#write.xlsx(final_data, "final_data.xlsx")
```




